### ISSUE TITLE
Use MemAvailiable instead of MemFree to get a more accurate picture of ram usage

### ISSUE THREAD

**Issue by olufskovnielsen** [2onk/InfoToolbar#1]
https://github.com/2onk/InfoToolbar/blob/8217e1467f7183702dc3867c4fe97ad157e24b2a/src/main/java/com/dasa/infotoolbar/impl/MemLoad.java#L26

https://www.baeldung.com/linux/free-available-cached-memory

**Comment by 2onk** [comment]
Hello olufskovnielsen,

thank you very much for reporting this and making me aware of it. 
I really appreciate it!

It is changed to memAvailable and I also changed a bit the information in the toolbar. Readme also updated.
